### ISSUE TITLE
[v2]  `Input 'scheme' and 'docker_image' cannot co-exist.` if `scheme` not specified

### ISSUE THREAD

**Issue by olifre** [xu-cheng/texlive-action#13]
As of https://github.com/xu-cheng/texlive-action/commit/373abd0411409d69fe9d56fa933c0912bc400e66 , the following snippet (almost straight from the docs) fails:
```yml
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v2
        with:
          docker_image: ghcr.io/xu-cheng/texlive-full:20230801
          run: |
            apk add make
            echo "foo"
```

Relevant lines from action log:
```
Run "${GITHUB_ACTION_PATH}/action.sh"
  "${GITHUB_ACTION_PATH}/action.sh"
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    INPUT_RUN: apk add make
  echo "foo"
  
    INPUT_SCHEME: full
    INPUT_TEXLIVE_VERSION: 
    INPUT_DOCKER_IMAGE: ghcr.io/xu-cheng/texlive-full:20230801
Error:  Input 'scheme' and 'docker_image' cannot co-exist.
Error: Process completed with exit code 1.
```

Full action log: https://github.com/olifre/texlive-text/actions/runs/6462937391/job/17545332493
Sample `yml`: https://github.com/olifre/texlive-text/blob/3351aa15d4559fc72a842c747aa60d4480b9d8e1/.github/workflows/test.yml

The following snippet works:
```yml
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme:
          docker_image: ghcr.io/xu-cheng/texlive-full:20230801
          run: |
            apk add make
            echo "foo"
```

Reasoning: I think `scheme` defaults to `full` in `action.yml`, which causes:
https://github.com/xu-cheng/texlive-action/blob/3105d92be19efba92810ce98cdea303ee8bb937e/action.sh#L23
to always error out when `docker_image` is set unless `scheme` is explicitly unset by the user at the same time.
