### ISSUE TITLE
using pdflatex, xelatex, etc in next steps

### ISSUE THREAD

**Issue by cmhughes** [xu-cheng/texlive-action#14]
Thank you for the useful action! :)

Consider the following minimal github action

```yaml
name: cmh-deploy-gh-pages

on:
  push:

jobs:
  cmh-preTeXt-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install TeX Live
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
           pdflatex --version
      - name: check latex executables
        run: |
          pdflatex --version
```

The above fails, as the second step doesn't know about the first step.

question
-
How can I access the texlive installation in the next (and subsequent steps)?

actual repo example
-
In case it's helpful, my sandbox use case is at https://github.com/cmhughes/preTeXt-cmh-explore

(I'm really sorry if this is a basic github actions question!)
