### ISSUE TITLE
Want to run test.py test file in an environment with texlive and python (rich library)

### ISSUE THREAD

**Issue by YanMing-lxb** [xu-cheng/texlive-action#15]
想在一个有texlive 和 python （rich库）的环境中运行test.py 测试文件

```yml
name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Specify the Python version you want to use
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install rich
    
    - name: Install TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full

    - name: Run tests
      run: |
        python tests/test.py
```
这是我之前写的，但是每次测试都要从头安装 texlive ，我想用您的 texlive-active，尝试了几个小时都不成功，所以想冒昧讨教！
