### ISSUE TITLE
[feature request] Allow only the installation of latex and other texlive binaries to PATH

### ISSUE THREAD

**Issue by kaushalmodi** [xu-cheng/texlive-action#6]
Hello,

Can you please allow a way to install `latex` and `dvisvgm` to the PATH so that other `run` commands can directly use those executables from PATH directly?

Here's what I tried and the Action failed saying the `latex` was not found:

```yaml
    steps:
      - uses: actions/checkout@v2
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: xu-cheng/texlive-action/full@v1 # For Org tests with `tex:dvisvgm` export option
      - name: Run tests
        run: |
          export PATH="/tmp/${USER}/ox-hugo-dev/pandoc/bin:${PATH}"
          make --no-print-directory -j1 test
```

[full yaml file](https://github.com/kaushalmodi/ox-hugo/blob/dvisvgm-support/.github/workflows/test.yml)

In my usecase, I don't invoke latex manually. Above, I am installing emacs, and then latex, and then when the "Run tests" `make` runs, it calls emacs in batch mode, which runs a bunch of tests via elisp code. One of those tests requires to run `latex` and `dvisvgm`. There, emacs throws this error:

```
[ox-hugo] 166/ Exporting ‘Equations exported to SVG (dvisvgm)’ ..
Creating LaTeX Image...
Debugger entered--Lisp error: (error "Can’t find ‘latex’ (you need to install the progra...")
  signal(error ("Can’t find ‘latex’ (you need to install the progra..."))
  error("Can't find `%s'%s" "latex" " (you need to install the programs: latex and dvis...")
  org-create-formula-image("\\[ a + b \\]" "/home/runner/work/ox-hugo/ox-hugo/test/site/conten..." (:foreground default :background default :scale 1.0 :html-foreground "Black" :html-background 
```

[full log](https://github.com/kaushalmodi/ox-hugo/runs/4698616531)

---

**Summary**: Allow a way to put `latex` and `dvisvgm` in the PATH so that any of the future `run` commands out of the scope of `- uses: xu-cheng/texlive-action/full@v1` can work.

**Comment by xu-cheng** [comment]
Sorry, but this is not how this action works.  This action works by running the code inside a docker container. Therefore, it has not effects on other actions. What you need is probably something like this:

```yaml
steps:
  - uses: actions/checkout@v2
  - uses: xu-cheng/texlive-action/full@v1 
    with:
      run: |
        apk add make emacs # you need to install emacs and any other required tools inside the docker container
        make --no-print-directory -j1 test 

```

**Comment by kaushalmodi** [comment]
That's unfortunate.. installing emacs within texlive docker will get complicated because right now I can easily runs my tests through a matrix of emacs versions using just

```yaml
  - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
```

I will need to remove these latex dependent tests from the online CI then :(

**Comment by xu-cheng** [comment]
You could try to run the entire workflow inside docker container.

```yaml
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xu-cheng/texlive-full:latest
    steps:
      - run: |
          # you may need to install tools used by other actions first. such as
          apk add git
      - uses: actions/checkout@v2
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - run: |
          apk add make
          make
```

I haven't test it. So not sure whether this will work. Noted that the docker image is based Alpine instead of Ubuntu.
