### ISSUE TITLE
Fail to use action in act-cli

### ISSUE THREAD

**Issue by alanlivio** [xu-cheng/texlive-action#7]
[act-cli](https://github.com/nektos/act) is a tool to run actions locally.
I failed to run texlive-action in it.

Workflow example
```
jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xu-cheng/texlive-action/full@v1
         with:
           run: 
             latexmk -shell-escape -cd -pdf file.tex
```

Run act:
```
$ act -v 
```

Error
```
[gh-pages.yml/gh-pages]   ❌  Failure - Main xu-cheng/texlive-action/full@v1
[gh-pages.yml/gh-pages] exit with `FAILURE`: 127
```
